/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-sqlite'
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from '@payloadcms/db-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-sqlite/drizzle'

export const users_sessions = sqliteTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = sqliteTable(
  'users',
  {
    id: integer('id').primaryKey(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text('email').notNull(),
    resetPasswordToken: text('reset_password_token'),
    resetPasswordExpiration: text('reset_password_expiration').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text('salt'),
    hash: text('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = sqliteTable(
  'media',
  {
    id: integer('id').primaryKey(),
    alt: text('alt').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const news_blocks_text_block = sqliteTable(
  'news_blocks_text_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    text: text('text', { mode: 'json' }).notNull(),
    blockName: text('block_name'),
  },
  (columns) => [
    index('news_blocks_text_block_order_idx').on(columns._order),
    index('news_blocks_text_block_parent_id_idx').on(columns._parentID),
    index('news_blocks_text_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [news.id],
      name: 'news_blocks_text_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const news_blocks_large_text_block = sqliteTable(
  'news_blocks_large_text_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    content: text('content').notNull(),
    isHighlight: integer('is_highlight', { mode: 'boolean' }).default(false),
    blockName: text('block_name'),
  },
  (columns) => [
    index('news_blocks_large_text_block_order_idx').on(columns._order),
    index('news_blocks_large_text_block_parent_id_idx').on(columns._parentID),
    index('news_blocks_large_text_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [news.id],
      name: 'news_blocks_large_text_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const news_blocks_image_block = sqliteTable(
  'news_blocks_image_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: text('caption'),
    blockName: text('block_name'),
  },
  (columns) => [
    index('news_blocks_image_block_order_idx').on(columns._order),
    index('news_blocks_image_block_parent_id_idx').on(columns._parentID),
    index('news_blocks_image_block_path_idx').on(columns._path),
    index('news_blocks_image_block_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [news.id],
      name: 'news_blocks_image_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const news_gallery = sqliteTable(
  'news_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: text('caption'),
  },
  (columns) => [
    index('news_gallery_order_idx').on(columns._order),
    index('news_gallery_parent_id_idx').on(columns._parentID),
    index('news_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [news.id],
      name: 'news_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const news = sqliteTable(
  'news',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    publishedDate: text('published_date')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    category: text('category', { enum: ['publications', 'announcements', 'official'] }).notNull(),
    shortDescription: text('short_description').notNull(),
    mainImage: integer('main_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    isPublished: integer('is_published', { mode: 'boolean' }).default(true),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('news_main_image_idx').on(columns.mainImage),
    index('news_updated_at_idx').on(columns.updatedAt),
    index('news_created_at_idx').on(columns.createdAt),
  ],
)

export const missionary_projects_directions = sqliteTable(
  'missionary_projects_directions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    direction: text('direction'),
  },
  (columns) => [
    index('missionary_projects_directions_order_idx').on(columns._order),
    index('missionary_projects_directions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [missionary_projects.id],
      name: 'missionary_projects_directions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const missionary_projects_gallery = sqliteTable(
  'missionary_projects_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('missionary_projects_gallery_order_idx').on(columns._order),
    index('missionary_projects_gallery_parent_id_idx').on(columns._parentID),
    index('missionary_projects_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [missionary_projects.id],
      name: 'missionary_projects_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const missionary_projects_reports = sqliteTable(
  'missionary_projects_reports',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    year: text('year').notNull(),
    file: text('file').notNull(),
  },
  (columns) => [
    index('missionary_projects_reports_order_idx').on(columns._order),
    index('missionary_projects_reports_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [missionary_projects.id],
      name: 'missionary_projects_reports_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const missionary_projects = sqliteTable(
  'missionary_projects',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    logo: integer('logo_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    shortDescription: text('short_description').notNull(),
    aboutUs: text('about_us', { mode: 'json' }).notNull(),
    status: text('status', { enum: ['active', 'completed'] }).default('active'),
    socialLinks_facebook: text('social_links_facebook')
      .notNull()
      .default('https://www.facebook.com/'),
    socialLinks_instagram: text('social_links_instagram'),
    socialLinks_phone: text('social_links_phone'),
    socialLinks_whatsapp: text('social_links_whatsapp'),
    socialLinks_viber: text('social_links_viber'),
    socialLinks_youtube: text('social_links_youtube'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('missionary_projects_logo_idx').on(columns.logo),
    index('missionary_projects_updated_at_idx').on(columns.updatedAt),
    index('missionary_projects_created_at_idx').on(columns.createdAt),
  ],
)

export const photo_reports_gallery = sqliteTable(
  'photo_reports_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('photo_reports_gallery_order_idx').on(columns._order),
    index('photo_reports_gallery_parent_id_idx').on(columns._parentID),
    index('photo_reports_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [photo_reports.id],
      name: 'photo_reports_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const photo_reports = sqliteTable(
  'photo_reports',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    date: text('date')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    coverImage: integer('cover_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    description: text('description'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('photo_reports_cover_image_idx').on(columns.coverImage),
    index('photo_reports_updated_at_idx').on(columns.updatedAt),
    index('photo_reports_created_at_idx').on(columns.createdAt),
  ],
)

export const prayer_requests_names = sqliteTable(
  'prayer_requests_names',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    name: text('name'),
  },
  (columns) => [
    index('prayer_requests_names_order_idx').on(columns._order),
    index('prayer_requests_names_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [prayer_requests.id],
      name: 'prayer_requests_names_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const prayer_requests = sqliteTable(
  'prayer_requests',
  {
    id: integer('id').primaryKey(),
    type: text('type', { enum: ['health', 'repose'] }).notNull(),
    service: text('service').notNull(),
    email: text('email').notNull(),
    amount: numeric('amount', { mode: 'number' }),
    currency: text('currency', { enum: ['UAH', 'EUR', 'USD'] }).default('UAH'),
    status: text('status', { enum: ['pending', 'paid', 'failed', 'printed'] }).default('pending'),
    printedAt: text('printed_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('prayer_requests_updated_at_idx').on(columns.updatedAt),
    index('prayer_requests_created_at_idx').on(columns.createdAt),
  ],
)

export const join_requests = sqliteTable(
  'join_requests',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    phone: text('phone'),
    email: text('email'),
    message: text('message'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('join_requests_updated_at_idx').on(columns.updatedAt),
    index('join_requests_created_at_idx').on(columns.createdAt),
  ],
)

export const questions = sqliteTable(
  'questions',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull(),
    question: text('question').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('questions_updated_at_idx').on(columns.updatedAt),
    index('questions_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = sqliteTable(
  'payload_kv',
  {
    id: integer('id').primaryKey(),
    key: text('key').notNull(),
    data: text('data', { mode: 'json' }).notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = sqliteTable(
  'payload_locked_documents',
  {
    id: integer('id').primaryKey(),
    globalSlug: text('global_slug'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = sqliteTable(
  'payload_locked_documents_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    newsID: integer('news_id'),
    'missionary-projectsID': integer('missionary_projects_id'),
    'photo-reportsID': integer('photo_reports_id'),
    'prayer-requestsID': integer('prayer_requests_id'),
    'join-requestsID': integer('join_requests_id'),
    questionsID: integer('questions_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_news_id_idx').on(columns.newsID),
    index('payload_locked_documents_rels_missionary_projects_id_idx').on(
      columns['missionary-projectsID'],
    ),
    index('payload_locked_documents_rels_photo_reports_id_idx').on(columns['photo-reportsID']),
    index('payload_locked_documents_rels_prayer_requests_id_idx').on(columns['prayer-requestsID']),
    index('payload_locked_documents_rels_join_requests_id_idx').on(columns['join-requestsID']),
    index('payload_locked_documents_rels_questions_id_idx').on(columns.questionsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['newsID']],
      foreignColumns: [news.id],
      name: 'payload_locked_documents_rels_news_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['missionary-projectsID']],
      foreignColumns: [missionary_projects.id],
      name: 'payload_locked_documents_rels_missionary_projects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['photo-reportsID']],
      foreignColumns: [photo_reports.id],
      name: 'payload_locked_documents_rels_photo_reports_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['prayer-requestsID']],
      foreignColumns: [prayer_requests.id],
      name: 'payload_locked_documents_rels_prayer_requests_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['join-requestsID']],
      foreignColumns: [join_requests.id],
      name: 'payload_locked_documents_rels_join_requests_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['questionsID']],
      foreignColumns: [questions.id],
      name: 'payload_locked_documents_rels_questions_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = sqliteTable(
  'payload_preferences',
  {
    id: integer('id').primaryKey(),
    key: text('key'),
    value: text('value', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = sqliteTable(
  'payload_preferences_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = sqliteTable(
  'payload_migrations',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const live_stream = sqliteTable('live_stream', {
  id: integer('id').primaryKey(),
  isManuallyLive: integer('is_manually_live', { mode: 'boolean' }).default(false),
  enableSundaySchedule: integer('enable_sunday_schedule', { mode: 'boolean' }).default(true),
  plannedEvent_startTime: text('planned_event_start_time').default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  plannedEvent_endTime: text('planned_event_end_time').default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  sundayStartTime: text('sunday_start_time').default('09:30'),
  sundayEndTime: text('sunday_end_time').default('12:30'),
  youtubeLink: text('youtube_link').notNull().default('https://www.youtube.com/@chernectvo_volyni'),
  channelID: text('channel_i_d').notNull().default('UC...'),
  message: text('message').default('Зараз триває пряма трансляція богослужіння'),
  syncStats_lastSyncedAt: text('sync_stats_last_synced_at').default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  syncStats_itemsFetched: numeric('sync_stats_items_fetched', { mode: 'number' }),
  cachedData_videos: text('cached_data_videos', { mode: 'json' }),
  cachedData_streams: text('cached_data_streams', { mode: 'json' }),
  cachedData_latestLiveStatus: integer('cached_data_latest_live_status', { mode: 'boolean' }),
  cachedData_lastUpdated: text('cached_data_last_updated').default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  updatedAt: text('updated_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
})

export const legal_settings_privacy_content_sections = sqliteTable(
  'legal_settings_privacy_content_sections',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    titleUA: text('title_u_a'),
    titleEN: text('title_e_n'),
    textUA: text('text_u_a'),
    textEN: text('text_e_n'),
  },
  (columns) => [
    index('legal_settings_privacy_content_sections_order_idx').on(columns._order),
    index('legal_settings_privacy_content_sections_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_settings.id],
      name: 'legal_settings_privacy_content_sections_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_settings_terms_content_sections = sqliteTable(
  'legal_settings_terms_content_sections',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    titleUA: text('title_u_a'),
    titleEN: text('title_e_n'),
    textUA: text('text_u_a'),
    textEN: text('text_e_n'),
  },
  (columns) => [
    index('legal_settings_terms_content_sections_order_idx').on(columns._order),
    index('legal_settings_terms_content_sections_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_settings.id],
      name: 'legal_settings_terms_content_sections_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_settings_refund_content_sections = sqliteTable(
  'legal_settings_refund_content_sections',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    titleUA: text('title_u_a'),
    titleEN: text('title_e_n'),
    textUA: text('text_u_a'),
    textEN: text('text_e_n'),
  },
  (columns) => [
    index('legal_settings_refund_content_sections_order_idx').on(columns._order),
    index('legal_settings_refund_content_sections_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [legal_settings.id],
      name: 'legal_settings_refund_content_sections_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const legal_settings = sqliteTable('legal_settings', {
  id: integer('id').primaryKey(),
  organization_legalEntityName: text('organization_legal_entity_name')
    .notNull()
    .default('Релігійна організація «Свято-Миколаївський Жидичинський чоловічий монастир»'),
  organization_edrpouCode: text('organization_edrpou_code').notNull(),
  organization_legalAddress: text('organization_legal_address')
    .notNull()
    .default('45240, Волинська область, Луцький р-н, с. Жидичин, вул. Ковельська, 1'),
  contacts_contactEmail: text('contacts_contact_email').notNull(),
  contacts_dpoContact: text('contacts_dpo_contact'),
  providers_paymentProvider: text('providers_payment_provider').default('WayForPay'),
  providers_hostingProvider: text('providers_hosting_provider').default('Netlify'),
  providers_analyticsServices: text('providers_analytics_services').default('Google Analytics'),
  refund_maxRefundDays: numeric('refund_max_refund_days', { mode: 'number' }).default(14),
  refund_refundProcessingDays: numeric('refund_refund_processing_days', { mode: 'number' }).default(
    10,
  ),
  lastUpdatedDate: text('last_updated_date')
    .notNull()
    .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  privacyContent_titleUA: text('privacy_content_title_u_a'),
  privacyContent_titleEN: text('privacy_content_title_e_n'),
  privacyContent_subtitleUA: text('privacy_content_subtitle_u_a'),
  privacyContent_subtitleEN: text('privacy_content_subtitle_e_n'),
  termsContent_titleUA: text('terms_content_title_u_a'),
  termsContent_titleEN: text('terms_content_title_e_n'),
  termsContent_subtitleUA: text('terms_content_subtitle_u_a'),
  termsContent_subtitleEN: text('terms_content_subtitle_e_n'),
  refundContent_titleUA: text('refund_content_title_u_a'),
  refundContent_titleEN: text('refund_content_title_e_n'),
  refundContent_subtitleUA: text('refund_content_subtitle_u_a'),
  refundContent_subtitleEN: text('refund_content_subtitle_e_n'),
  updatedAt: text('updated_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
})

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_news_blocks_text_block = relations(news_blocks_text_block, ({ one }) => ({
  _parentID: one(news, {
    fields: [news_blocks_text_block._parentID],
    references: [news.id],
    relationName: '_blocks_textBlock',
  }),
}))
export const relations_news_blocks_large_text_block = relations(
  news_blocks_large_text_block,
  ({ one }) => ({
    _parentID: one(news, {
      fields: [news_blocks_large_text_block._parentID],
      references: [news.id],
      relationName: '_blocks_largeTextBlock',
    }),
  }),
)
export const relations_news_blocks_image_block = relations(news_blocks_image_block, ({ one }) => ({
  _parentID: one(news, {
    fields: [news_blocks_image_block._parentID],
    references: [news.id],
    relationName: '_blocks_imageBlock',
  }),
  image: one(media, {
    fields: [news_blocks_image_block.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_news_gallery = relations(news_gallery, ({ one }) => ({
  _parentID: one(news, {
    fields: [news_gallery._parentID],
    references: [news.id],
    relationName: 'gallery',
  }),
  image: one(media, {
    fields: [news_gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_news = relations(news, ({ one, many }) => ({
  mainImage: one(media, {
    fields: [news.mainImage],
    references: [media.id],
    relationName: 'mainImage',
  }),
  _blocks_textBlock: many(news_blocks_text_block, {
    relationName: '_blocks_textBlock',
  }),
  _blocks_largeTextBlock: many(news_blocks_large_text_block, {
    relationName: '_blocks_largeTextBlock',
  }),
  _blocks_imageBlock: many(news_blocks_image_block, {
    relationName: '_blocks_imageBlock',
  }),
  gallery: many(news_gallery, {
    relationName: 'gallery',
  }),
}))
export const relations_missionary_projects_directions = relations(
  missionary_projects_directions,
  ({ one }) => ({
    _parentID: one(missionary_projects, {
      fields: [missionary_projects_directions._parentID],
      references: [missionary_projects.id],
      relationName: 'directions',
    }),
  }),
)
export const relations_missionary_projects_gallery = relations(
  missionary_projects_gallery,
  ({ one }) => ({
    _parentID: one(missionary_projects, {
      fields: [missionary_projects_gallery._parentID],
      references: [missionary_projects.id],
      relationName: 'gallery',
    }),
    image: one(media, {
      fields: [missionary_projects_gallery.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_missionary_projects_reports = relations(
  missionary_projects_reports,
  ({ one }) => ({
    _parentID: one(missionary_projects, {
      fields: [missionary_projects_reports._parentID],
      references: [missionary_projects.id],
      relationName: 'reports',
    }),
  }),
)
export const relations_missionary_projects = relations(missionary_projects, ({ one, many }) => ({
  logo: one(media, {
    fields: [missionary_projects.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  directions: many(missionary_projects_directions, {
    relationName: 'directions',
  }),
  gallery: many(missionary_projects_gallery, {
    relationName: 'gallery',
  }),
  reports: many(missionary_projects_reports, {
    relationName: 'reports',
  }),
}))
export const relations_photo_reports_gallery = relations(photo_reports_gallery, ({ one }) => ({
  _parentID: one(photo_reports, {
    fields: [photo_reports_gallery._parentID],
    references: [photo_reports.id],
    relationName: 'gallery',
  }),
  image: one(media, {
    fields: [photo_reports_gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_photo_reports = relations(photo_reports, ({ one, many }) => ({
  coverImage: one(media, {
    fields: [photo_reports.coverImage],
    references: [media.id],
    relationName: 'coverImage',
  }),
  gallery: many(photo_reports_gallery, {
    relationName: 'gallery',
  }),
}))
export const relations_prayer_requests_names = relations(prayer_requests_names, ({ one }) => ({
  _parentID: one(prayer_requests, {
    fields: [prayer_requests_names._parentID],
    references: [prayer_requests.id],
    relationName: 'names',
  }),
}))
export const relations_prayer_requests = relations(prayer_requests, ({ many }) => ({
  names: many(prayer_requests_names, {
    relationName: 'names',
  }),
}))
export const relations_join_requests = relations(join_requests, () => ({}))
export const relations_questions = relations(questions, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    newsID: one(news, {
      fields: [payload_locked_documents_rels.newsID],
      references: [news.id],
      relationName: 'news',
    }),
    'missionary-projectsID': one(missionary_projects, {
      fields: [payload_locked_documents_rels['missionary-projectsID']],
      references: [missionary_projects.id],
      relationName: 'missionary-projects',
    }),
    'photo-reportsID': one(photo_reports, {
      fields: [payload_locked_documents_rels['photo-reportsID']],
      references: [photo_reports.id],
      relationName: 'photo-reports',
    }),
    'prayer-requestsID': one(prayer_requests, {
      fields: [payload_locked_documents_rels['prayer-requestsID']],
      references: [prayer_requests.id],
      relationName: 'prayer-requests',
    }),
    'join-requestsID': one(join_requests, {
      fields: [payload_locked_documents_rels['join-requestsID']],
      references: [join_requests.id],
      relationName: 'join-requests',
    }),
    questionsID: one(questions, {
      fields: [payload_locked_documents_rels.questionsID],
      references: [questions.id],
      relationName: 'questions',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_live_stream = relations(live_stream, () => ({}))
export const relations_legal_settings_privacy_content_sections = relations(
  legal_settings_privacy_content_sections,
  ({ one }) => ({
    _parentID: one(legal_settings, {
      fields: [legal_settings_privacy_content_sections._parentID],
      references: [legal_settings.id],
      relationName: 'privacyContent_sections',
    }),
  }),
)
export const relations_legal_settings_terms_content_sections = relations(
  legal_settings_terms_content_sections,
  ({ one }) => ({
    _parentID: one(legal_settings, {
      fields: [legal_settings_terms_content_sections._parentID],
      references: [legal_settings.id],
      relationName: 'termsContent_sections',
    }),
  }),
)
export const relations_legal_settings_refund_content_sections = relations(
  legal_settings_refund_content_sections,
  ({ one }) => ({
    _parentID: one(legal_settings, {
      fields: [legal_settings_refund_content_sections._parentID],
      references: [legal_settings.id],
      relationName: 'refundContent_sections',
    }),
  }),
)
export const relations_legal_settings = relations(legal_settings, ({ many }) => ({
  privacyContent_sections: many(legal_settings_privacy_content_sections, {
    relationName: 'privacyContent_sections',
  }),
  termsContent_sections: many(legal_settings_terms_content_sections, {
    relationName: 'termsContent_sections',
  }),
  refundContent_sections: many(legal_settings_refund_content_sections, {
    relationName: 'refundContent_sections',
  }),
}))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  news_blocks_text_block: typeof news_blocks_text_block
  news_blocks_large_text_block: typeof news_blocks_large_text_block
  news_blocks_image_block: typeof news_blocks_image_block
  news_gallery: typeof news_gallery
  news: typeof news
  missionary_projects_directions: typeof missionary_projects_directions
  missionary_projects_gallery: typeof missionary_projects_gallery
  missionary_projects_reports: typeof missionary_projects_reports
  missionary_projects: typeof missionary_projects
  photo_reports_gallery: typeof photo_reports_gallery
  photo_reports: typeof photo_reports
  prayer_requests_names: typeof prayer_requests_names
  prayer_requests: typeof prayer_requests
  join_requests: typeof join_requests
  questions: typeof questions
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  live_stream: typeof live_stream
  legal_settings_privacy_content_sections: typeof legal_settings_privacy_content_sections
  legal_settings_terms_content_sections: typeof legal_settings_terms_content_sections
  legal_settings_refund_content_sections: typeof legal_settings_refund_content_sections
  legal_settings: typeof legal_settings
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_news_blocks_text_block: typeof relations_news_blocks_text_block
  relations_news_blocks_large_text_block: typeof relations_news_blocks_large_text_block
  relations_news_blocks_image_block: typeof relations_news_blocks_image_block
  relations_news_gallery: typeof relations_news_gallery
  relations_news: typeof relations_news
  relations_missionary_projects_directions: typeof relations_missionary_projects_directions
  relations_missionary_projects_gallery: typeof relations_missionary_projects_gallery
  relations_missionary_projects_reports: typeof relations_missionary_projects_reports
  relations_missionary_projects: typeof relations_missionary_projects
  relations_photo_reports_gallery: typeof relations_photo_reports_gallery
  relations_photo_reports: typeof relations_photo_reports
  relations_prayer_requests_names: typeof relations_prayer_requests_names
  relations_prayer_requests: typeof relations_prayer_requests
  relations_join_requests: typeof relations_join_requests
  relations_questions: typeof relations_questions
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_live_stream: typeof relations_live_stream
  relations_legal_settings_privacy_content_sections: typeof relations_legal_settings_privacy_content_sections
  relations_legal_settings_terms_content_sections: typeof relations_legal_settings_terms_content_sections
  relations_legal_settings_refund_content_sections: typeof relations_legal_settings_refund_content_sections
  relations_legal_settings: typeof relations_legal_settings
}

declare module '@payloadcms/db-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
